WebClient/Models/ErrorViewModel.cs
using System;

namespace WebClient.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebClient/Controllers/CarController.cs
using Core.Interfaces;
using Domain;
using Microsoft.AspNetCore.Mvc;

namespace WebClient.Controllers
{
    [Route("web/[controller]")]

    public class CarController : Controller
    {
        private readonly IRepository _carRepo;

        public CarController(IRepository carRepo)
        {
            _carRepo = carRepo;
        }

        [Route("", Name = "Cars")]
        [HttpGet]
        public IActionResult Cars()
        {
            var cars = _carRepo.GetAll();
            return View(cars);
        }

        [Route("/create", Name = "CreateCar")]
        [HttpGet]
        public IActionResult CreateCar()
        {
            return View();
        }

        [HttpPost]
        [Route("/create", Name = "PostCar")]
        public IActionResult CreateCar(Car car)
        {
            _carRepo.Add(car);
            return RedirectToRoute("Cars");
        }

        [HttpGet]
        [Route("/delete/{id}/confirm", Name = "DeleteConfirmation")]

        public IActionResult _DeleteCar(int id)
        {
            var toDelete = _carRepo.GetById(id);
            return PartialView(toDelete);
        }

        [HttpPost]
        [Route("/delete/{id}", Name="DeleteCar")]
        public IActionResult DeleteCar(int id)
        {
            _carRepo.Delete(_carRepo.GetById(id));
            return RedirectToRoute("Cars");
        }

        [HttpGet]
        [Route("/update/{id}", Name = "UpdateCar")]
        public IActionResult UpdateCar(int id)
        {
            var toUpdate = _carRepo.GetById(id);
            return View(toUpdate);
        }

        [HttpPost]
        [Route("/update/{id}", Name = "PutCar")]
        public IActionResult UpdateCar(Car car)
        {
            _carRepo.Update(car);
            return RedirectToRoute("Cars");
        }
    }
}

WebClient/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebClient.Models;

namespace WebClient.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebClient/Views/Car/Cars.cshtml
@model DataStructure.List;

@{
    ViewData["Title"] = "Cars";
}
<div style="margin-top:50px;">

    <p>
        <a asp-route="CreateCar"><span class="glyphicon glyphicon-plus"></span></a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Make</th>
                <th>Model</th>
                <th>Year</th>
                <th colspan="2">Commands</th>
            </tr>
        </thead>
        <tbody>
            @{
                var ctr = 1;
                var current = Model.First;
                while (current != null)
                {
                    <tr>
                        <td> @ctr</td>
                        <td> @current.Data.Make</td>
                        <td> @current.Data.Model</td>
                        <td> @current.Data.Year</td>
                        <td><a asp-route="DeleteConfirmation" asp-route-id="@current.Data.Id"><span class="glyphicon glyphicon-remove"></span></a></td>
                        <td><a asp-route="UpdateCar" asp-route-id="@current.Data.Id"><span class="glyphicon glyphicon-pencil"></span></a></td>
                    </tr>
                    current = current.Next;
                    ctr += 1;
                }
            }
        </tbody>
    </table>
</div>

WebClient/Views/Car/CreateCar.cshtml
@model Domain.Car

@{
    ViewData["Title"] = "CreateCar";
}

<h2>CreateCar</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-route="PostCar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Make" class="control-label"></label>
                <input asp-for="Make" class="form-control" />
                <span asp-validation-for="Make" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Cars">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebClient/Views/Car/UpdateCar.cshtml
@model Domain.Car

@{
    ViewData["Title"] = "UpdateCar";
}

<h2>UpdateCar</h2>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateCar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Make" class="control-label"></label>
                <input asp-for="Make" class="form-control" />
                <span asp-validation-for="Make" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Cars">Back to List</a>
</div>

WebClient/Views/Car/_DeleteCar.cshtml
@model Domain.Car

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Car</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Make)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Make)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>
    </dl>
    
    <form asp-action="DeleteCar">
        <input type="submit" value="Delete" class="btn btn-default" /> 
        <a asp-action="Cars">Back to List</a>
    </form>
</div>

WebClient/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

WebClient/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebClient/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

WebClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebClient</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Car" asp-action="Cars" class="navbar-brand">Cars</a>
            </div>
            @*<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>*@
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - WebClient</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>